import type { MarketplaceListing } from "./types";

export const DEMO_LISTINGS: MarketplaceListing[] = [
  {
    id: "ovv-andina-revision",
    kind: "ovv_profile",
    tab: "ovv",
    title: "Andina Revisión Técnica",
    organization: "Andina Revisión Técnica",
    entityType: "OVV",
    description:
      "Organismo independiente que declara servicios de preevaluación, validación y verificación para iniciativas forestales en Colombia. Perfil demostrativo para el MVP.",
    services: ["Preevaluación", "Validación", "Verificación"],
    sectors: ["Conservación", "Restauración forestal"],
    coverage: "Colombia",
    languages: ["Español"],
    modality: "Híbrida",
    accreditation: "No verificada en CarbonFlow",
    accreditor: "Declarada por la entidad",
    accreditationScope: "Mitigación forestal — alcance declarado",
    experienceNote: "Experiencia declarada en conservación y restauración, número de proyectos no publicado.",
    updatedAt: "2026-07-12",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "firma-orinoquia-linea-base",
    kind: "technical_firm_profile",
    tab: "ovv",
    title: "Orinoquía Línea Base",
    organization: "Orinoquía Línea Base",
    entityType: "Firma técnica",
    description:
      "Firma técnica que declara apoyo en línea base, documentación de control y preparación para revisión externa. No es una OVV acreditada en CarbonFlow.",
    services: ["Preevaluación"],
    sectors: ["Conservación", "Restauración"],
    coverage: "Región Orinoquía",
    languages: ["Español", "Inglés"],
    modality: "Campo",
    accreditation: "No verificada en CarbonFlow",
    publicDocumentUrl: "https://example.org/documentos-publicos-demo",
    updatedAt: "2026-06-28",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario", "Documento compartido por el titular"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "consultor-pacifico-salvaguardas",
    kind: "technical_firm_profile",
    tab: "ovv",
    title: "Pacífico Salvaguardas",
    organization: "Pacífico Salvaguardas",
    entityType: "Consultor especializado",
    description:
      "Consultoría especializada en salvaguardas sociales y ambientales para iniciativas de restauración. Perfil demostrativo.",
    services: ["Preevaluación"],
    sectors: ["Restauración"],
    coverage: "Región Pacífico",
    languages: ["Español"],
    modality: "Remota",
    accreditation: "No verificada en CarbonFlow",
    updatedAt: "2026-05-19",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "proj-meta-restauracion",
    kind: "carbon_project_development",
    tab: "carbon",
    title: "Restauración de corredores en el Piedemonte del Meta",
    description:
      "Iniciativa en preparación avanzada que busca un comprador ancla y financiación de estructuración. No representa créditos emitidos.",
    location: "Meta, Colombia",
    initiativeType: "Restauración",
    projectStatus: "Preparación avanzada",
    areaHa: 125,
    co2eEstimate: 18400,
    co2eDisclaimer: "Estimación preliminar, no certificada",
    need: "Comprador ancla / Financiación de estructuración",
    cobenefits: ["Biodiversidad", "Comunidades", "Agua"],
    renareRef: "Referencia RENARE no iniciada",
    holderType: "Desarrollador",
    updatedAt: "2026-08-02",
    demo: true,
    trustLabels: ["En estructuración", "Requiere revisión técnica", "Información declarada por el usuario", "Perfil demostrativo"],
    publicationStatus: "Publicado",
    contactHidden: true,
    dataRoom: [
      { id: "resumen", name: "Resumen ejecutivo", shared: true },
      { id: "cronograma", name: "Cronograma preliminar", shared: true },
    ],
    dataRoomLevels: {
      public: [
        { id: "resumen", name: "Resumen ejecutivo", shared: true },
        { id: "tipo", name: "Tipo de iniciativa", shared: true },
      ],
      request: [
        { id: "diagnostico", name: "Diagnóstico geoespacial resumido", shared: false },
        { id: "cronograma", name: "Cronograma", shared: false },
        { id: "presupuesto", name: "Presupuesto agregado", shared: false },
      ],
      confidential: [{ id: "tenencia", name: "Soportes de control/tenencia", shared: false }],
    },
    readiness: {
      stage: "Preparación avanzada",
      validationScore: 72,
      diagnosisAvailable: true,
      formulationPct: 80,
      traceability: "Referencia RENARE no iniciada",
      shareableDocs: { available: 5, total: 8 },
      gaps: ["Metodología/estándar por definir", "Soporte de control del predio pendiente", "Salvaguardas por ampliar"],
      sources: ["Diagnóstico", "Formulación", "Validación y Registro"],
    },
  },
  {
    id: "proj-caqueta-conservacion",
    kind: "carbon_project_development",
    tab: "carbon",
    title: "Conservación comunitaria en Caquetá",
    description:
      "Proyecto en estructuración que busca alianza técnica y manifestación de interés para compra futura. Sin créditos emitidos.",
    location: "Caquetá, Colombia",
    initiativeType: "Conservación",
    projectStatus: "En estructuración",
    areaHa: 340,
    co2eEstimate: 51200,
    co2eDisclaimer: "Estimación preliminar, no certificada",
    need: "Alianza técnica / Compra futura",
    cobenefits: ["Comunidades", "Biodiversidad"],
    holderType: "Comunidad",
    beneficiariesEstimate: 120,
    participationMechanism: "Asamblea comunitaria declarada por el titular",
    benefitDistribution: "En construcción",
    needsTechnicalAssistance: true,
    needsSeedFinance: true,
    updatedAt: "2026-07-21",
    demo: true,
    trustLabels: ["En estructuración", "Información declarada por el usuario", "Perfil demostrativo", "Proyecto comunitario / Pequeño productor"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "proj-antioquia-reforestacion",
    kind: "carbon_project_development",
    tab: "carbon",
    title: "Reforestación de laderas en Oriente antioqueño",
    description:
      "Iniciativa lista para revisión técnica. Busca financiación de preparación y un aliado comercial no vinculante.",
    location: "Antioquia, Colombia",
    initiativeType: "Reforestación",
    projectStatus: "Listo para revisión técnica",
    areaHa: 86,
    co2eEstimate: 9800,
    co2eDisclaimer: "Estimación preliminar, no certificada",
    need: "Financiación",
    cobenefits: ["Agua", "Otros"],
    updatedAt: "2026-08-08",
    demo: true,
    trustLabels: ["Requiere revisión técnica", "Información declarada por el usuario", "Perfil demostrativo"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "credit-verra-demo",
    kind: "reported_carbon_result",
    tab: "carbon",
    title: "Resultado reportado — Conservación Andina (demo)",
    description:
      "Resultado de mitigación reportado en un registro externo de demostración. No constituye oferta de compra ni disponibilidad verificada por CarbonFlow.",
    location: "Cundinamarca, Colombia",
    initiativeType: "Conservación",
    registry: "Verra",
    externalId: "VCS-DEMO-10421",
    officialUrl: "https://registry.verra.org/",
    reportedStatus: "Créditos emitidos reportados",
    consultedAt: "2026-08-01",
    methodology: "Metodología pública de demostración",
    vintage: "2022-2023",
    volumeIssued: 12000,
    updatedAt: "2026-08-01",
    demo: true,
    trustLabels: [
      "Resultado reportado en registro externo",
      "Fuente oficial enlazada",
      "No constituye oferta vinculante",
      "Perfil demostrativo",
    ],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "credit-retired-demo",
    kind: "reported_retired_credit",
    tab: "carbon",
    title: "Resultado retirado — Restauración Caribe (demo)",
    description:
      "Créditos reportados como retirados en fuente externa. No disponibles para nueva asignación comercial.",
    location: "Bolívar, Colombia",
    initiativeType: "Restauración",
    registry: "Gold Standard",
    externalId: "GS-DEMO-7781",
    officialUrl: "https://registry.goldstandard.org/",
    reportedStatus: "Créditos retirados reportados",
    consultedAt: "2026-07-15",
    volumeIssued: 4500,
    volumeRetired: 4500,
    updatedAt: "2026-07-15",
    demo: true,
    trustLabels: [
      "Resultado reportado en registro externo",
      "Fuente oficial enlazada",
      "Retirado / no disponible para nueva asignación",
      "Perfil demostrativo",
    ],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "buyer-cafe-andino",
    kind: "carbon_buyer_demand",
    tab: "carbon",
    title: "Café Andino SAS",
    organization: "Café Andino SAS",
    entityType: "Empresa compradora",
    description:
      "Empresa de café que declara necesidad de conectar con un proyecto de conservación o restauración para compensar emisiones de su cadena. No es una orden de compra ni una oferta vinculante.",
    location: "Caldas, Colombia",
    initiativeType: "Conservación",
    sectors: ["Conservación", "Restauración"],
    tonsNeeded: 8000,
    budgetAmount: "1,200 millones",
    budgetCurrency: "COP",
    need: "Compensación de emisiones de alcance 3",
    updatedAt: "2026-08-10",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario", "No constituye oferta vinculante"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "buyer-logistica-caribe",
    kind: "carbon_buyer_demand",
    tab: "carbon",
    title: "Logística Caribe Ltda.",
    organization: "Logística Caribe Ltda.",
    entityType: "Empresa compradora",
    description:
      "Operador logístico que busca un proyecto forestal compatible con su meta de compensación 2026-2028. Presupuesto orientativo, sujeto a revisión del titular.",
    location: "Atlántico, Colombia",
    initiativeType: "Restauración",
    sectors: ["Restauración", "Reforestación"],
    tonsNeeded: 3500,
    budgetAmount: "180,000",
    budgetCurrency: "USD",
    need: "Compensación operativa anual",
    updatedAt: "2026-08-04",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario", "No constituye oferta vinculante"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "buyer-hoteles-pacifico",
    kind: "carbon_buyer_demand",
    tab: "carbon",
    title: "Grupo Hotelero Pacífico",
    organization: "Grupo Hotelero Pacífico",
    entityType: "Empresa compradora",
    description:
      "Cadena hotelera que declara interés en un proyecto comunitario de conservación. Busca conectar, no contratar ni reservar créditos en esta plataforma.",
    location: "Valle del Cauca, Colombia",
    initiativeType: "Conservación",
    sectors: ["Conservación"],
    tonsNeeded: 1200,
    budgetAmount: "400 millones",
    budgetCurrency: "COP",
    need: "Compensación de huella hotelera",
    updatedAt: "2026-07-22",
    demo: true,
    trustLabels: ["Perfil demostrativo", "Información declarada por el usuario", "No constituye oferta vinculante"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "fin-proj-guaviare",
    kind: "green_finance_project",
    tab: "finance",
    title: "Restauración de sabanas inundables — Guaviare",
    description:
      "Perfil financiable en estructuración. Busca deuda verde y asistencia técnica para línea base e implementación.",
    location: "Guaviare, Colombia",
    environmentalCategory: "Conservación/restauración de ecosistemas",
    projectStage: "Estructuración",
    indicativeAmount: "800–1,200 millones",
    currency: "COP",
    resourceUses: ["Estudios y diseño técnico", "Línea base y formulación", "Implementación", "Monitoreo y seguimiento"],
    financeTypes: ["Deuda verde", "Asistencia técnica"],
    areaHa: 210,
    co2eEstimate: 27600,
    cobenefits: ["Biodiversidad", "Comunidades"],
    projectStatus: "En búsqueda de financiación",
    updatedAt: "2026-08-05",
    demo: true,
    trustLabels: [
      "En búsqueda de financiación",
      "Información declarada por el usuario",
      "No constituye oferta de valores",
      "Perfil demostrativo",
    ],
    publicationStatus: "Publicado",
    contactHidden: true,
    dataRoom: [
      { id: "resumen", name: "Resumen ejecutivo", shared: true },
      { id: "diagnostico", name: "Diagnóstico geoespacial resumido", shared: true },
      { id: "presupuesto", name: "Presupuesto preliminar", shared: true },
      { id: "cronograma", name: "Cronograma", shared: true },
    ],
  },
  {
    id: "fin-proj-huila",
    kind: "green_finance_project",
    tab: "finance",
    title: "Eficiencia hídrica y restauración de cuencas — Huila",
    description:
      "Proyecto que declara necesidad de estructuración financiera y capital de impacto. Información preliminar.",
    location: "Huila, Colombia",
    environmentalCategory: "Gestión de agua",
    projectStage: "Preparación avanzada",
    indicativeAmount: "1.5–2.0 millones",
    currency: "USD",
    resourceUses: ["Implementación", "Equipos e infraestructura", "Costos de validación/verificación"],
    financeTypes: ["Capital de impacto", "Estructuración financiera"],
    areaHa: 64,
    cobenefits: ["Agua", "Comunidades"],
    projectStatus: "En búsqueda de financiación",
    updatedAt: "2026-07-30",
    demo: true,
    trustLabels: ["Información declarada por el usuario", "No constituye oferta de valores", "Perfil demostrativo"],
    publicationStatus: "Publicado",
    contactHidden: true,
    dataRoom: [{ id: "resumen", name: "Resumen ejecutivo", shared: true }],
  },
  {
    id: "fin-fondo-impacto-andino",
    kind: "green_finance_provider",
    tab: "finance",
    title: "Fondo de Impacto Andino",
    organization: "Fondo de Impacto Andino",
    entityType: "Fondo",
    description:
      "Fondo de demostración que declara interés en restauración, conservación y energía renovable. No es una oferta de valores.",
    instruments: ["Deuda de proyecto", "Asistencia técnica"],
    sectors: ["Restauración", "Conservación", "Energía renovable"],
    ticketRange: "COP 500 millones – 3,000 millones",
    coverage: "Colombia",
    projectStage: "Estructuración a implementación",
    evaluationCriteria: "Etapa, documentación mínima, uso de recursos y salvaguardas declaradas.",
    requiredDocuments: ["Resumen ejecutivo", "Presupuesto preliminar", "Cronograma"],
    updatedAt: "2026-06-14",
    demo: true,
    trustLabels: ["Información declarada por el usuario", "Perfil demostrativo"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
  {
    id: "fin-banco-demo-verde",
    kind: "green_finance_provider",
    tab: "finance",
    title: "Mesa Verde Estructuración",
    organization: "Mesa Verde Estructuración",
    entityType: "Estructurador",
    description:
      "Estructurador demostrativo de instrumentos de financiación verde y asistencia técnica. Perfil no verificado por CarbonFlow.",
    instruments: ["Estructuración financiera", "Garantía"],
    sectors: ["Conservación", "Economía circular/residuos"],
    ticketRange: "USD 250,000 – 2,000,000",
    coverage: "Colombia y región andina",
    updatedAt: "2026-05-03",
    demo: true,
    trustLabels: ["Información declarada por el usuario", "Perfil demostrativo"],
    publicationStatus: "Publicado",
    contactHidden: true,
  },
];

export function listingMatchesQuery(listing: MarketplaceListing, query: string) {
  if (!query.trim()) return true;
  const q = query.toLowerCase();
  const haystack = [
    listing.title,
    listing.organization,
    listing.entityType,
    listing.description,
    listing.location,
    listing.coverage,
    listing.initiativeType,
    listing.need,
    listing.registry,
    listing.externalId,
    listing.budgetAmount,
    listing.environmentalCategory,
    ...(listing.services ?? []),
    ...(listing.sectors ?? []),
    ...(listing.cobenefits ?? []),
    ...(listing.instruments ?? []),
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  return haystack.includes(q);
}
